drop database hoteldata;

CREATE DATABASE HOTELDATA;
USE HOTELDATA;

-- CUSTOMER table with all constraints
CREATE TABLE CUSTOMER (
    CUSID INT PRIMARY KEY,                     
    NAME VARCHAR(100) NOT NULL,                
    EMAIL VARCHAR(100) UNIQUE,                 
    FEES DECIMAL(10,2) CHECK (FEES >= 3000),   
    CLASS VARCHAR(50) DEFAULT 'STANDARD',      
    BOOKINGDATE DATE NOT NULL,
    ROOMID INT,                                
    FOREIGN KEY (ROOMID) REFERENCES ROOM(ROOMID)
);

INSERT INTO CUSTOMER VALUES
(1, 'John Doe', 'john@gmail.com', 15000, 'FIRST', '2023-01-10', 102),
(2, 'Alice Smith', 'alice@gmail.com', 6000, 'SECOND', '2022-12-01', 101),
(3, 'Bob Johnson', 'bob@gmail.com', 4500, 'THIRD', '2023-02-15', 103),
(4, 'Rahul Patel', 'rahul@gmail.com', 8000, DEFAULT, '2023-03-05', 101),
(5, 'Neha Shah', 'neha@gmail.com', 12000, 'FIRST', '2023-04-01', 102);

-- FEES greater than 5000
SELECT * FROM CUSTOMER WHERE FEES > 5000;

-- AND
SELECT * FROM CUSTOMER
WHERE FEES > 5000 AND CLASS = 'FIRST';

-- OR
SELECT * FROM CUSTOMER
WHERE CLASS = 'FIRST' OR CLASS = 'SECOND';

-- NOT
SELECT * FROM CUSTOMER
WHERE NOT CLASS = 'THIRD';

-- IN
SELECT * FROM CUSTOMER
WHERE CLASS IN ('FIRST', 'SECOND');

-- BETWEEN
SELECT * FROM CUSTOMER
WHERE FEES BETWEEN 5000 AND 12000;

-- DESC order
SELECT * FROM CUSTOMER
ORDER BY FEES DESC;

-- LIMIT
SELECT * FROM CUSTOMER
ORDER BY FEES DESC
LIMIT 3;

-- Add 10% service charge
SELECT NAME, FEES, FEES + (FEES * 0.10) AS TOTAL_AMOUNT
FROM CUSTOMER;

-- Discount example
SELECT NAME, FEES, FEES - 500 AS DISCOUNTED_FEES
FROM CUSTOMER;

SELECT COUNT(*) AS TOTAL_CUSTOMERS FROM CUSTOMER;

SELECT MIN(FEES) AS MIN_FEES FROM CUSTOMER;

SELECT MAX(FEES) AS MAX_FEES FROM CUSTOMER;

SELECT SUM(FEES) AS TOTAL_FEES FROM CUSTOMER;

SELECT AVG(FEES) AS AVERAGE_FEES FROM CUSTOMER;

-- Group by CLASS
SELECT CLASS, COUNT(*) AS TOTAL_CUSTOMERS
FROM CUSTOMER
GROUP BY CLASS;

-- HAVING
SELECT CLASS, AVG(FEES) AS AVG_FEES
FROM CUSTOMER
GROUP BY CLASS
HAVING AVG(FEES) > 7000;

-- UPDATE
UPDATE CUSTOMER
SET FEES = FEES + 1000
WHERE CLASS = 'SECOND';

-- DELETE specific record
DELETE FROM CUSTOMER
WHERE CUSID = 3;

SELECT C.CUSID, C.NAME, C.FEES, C.CLASS, R.ROOMTYPE
FROM CUSTOMER C
JOIN ROOM R
ON C.ROOMID = R.ROOMID;

