CREATE DATABASE SCHOOLDATA;

USE SCHOOLDATA;

CREATE TABLE STUDENTS(
    STDID INT PRIMARY KEY,
    NAME VARCHAR(100),
	FEES DECIMAL(10,2),
    COURSE VARCHAR(50),
    JoiningDate DATE
);

INSERT INTO STUDENTS (STDID, NAME, FEES, COURSE, JoiningDate) 
VALUES (1, 'John Doe', 50000.00, 'BCA', '2023-01-10');

INSERT INTO STUDENTS (STDID, NAME, FEES, COURSE, JoiningDate) 
VALUES 
(2, 'Alice Smith', 60000.00, 'BBA', '2022-12-01'),
(3, 'Bob Johnson', 55000.00, 'BCOM', '2023-02-15');


SELECT * FROM STUDENTS;

SELECT NAME, FEES FROM STUDENTS;

SELECT * FROM STUDENTS WHERE FEES > 50000;

SELECT * FROM STUDENTS ORDER BY FEES DESC;

UPDATE STUDENTS
SET FEES = 65000.00 
WHERE STDID = 2;

UPDATE STUDENTS 
SET COURSE = 'AI-ML' 
WHERE STDID = 1;

DELETE FROM STUDENTS WHERE STDID = 3;

DELETE FROM STUDENTS;



