CREATE DATABASE HOTELDATA;

USE HOTELDATA;

CREATE TABLE CUSTOMER(
    CUSID INT PRIMARY KEY,
    NAME VARCHAR(100),
	FEES DECIMAL(10,2),
    CLASS VARCHAR(50),
    BOOKINGDATE DATE
);

INSERT INTO CUSTOMER (CUSID, NAME, FEES, CLASS, BOOKINGDATE) 
VALUES (1, 'John Doe', 15000.00, 'FIRST', '2023-01-10');

INSERT INTO CUSTOMER (CUSID, NAME, FEES, CLASS, BOOKINGDATE) 
VALUES 
(2, 'Alice Smith', 6000.00, 'SECOND', '2022-12-01'),
(3, 'Bob Johnson', 4500.00, 'THIRD', '2023-02-15');


SELECT * FROM CUSTOMER;

SELECT NAME, FEES FROM CUSTOMER;

SELECT * FROM CUSTOMER WHERE FEES > 5000;

SELECT * FROM CUSTOMER ORDER BY FEES DESC;

UPDATE CUSTOMER
SET FEES = 6500.00 
WHERE CUSID = 2;

UPDATE CUSTOMER
SET CLASS = 'FIRSTONE' 
WHERE CUSID = 1;

DELETE FROM CUSTOMER WHERE CUSID = 3;

DELETE FROM CUSTOMER;
